apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  MONGO_URI: "mongodb://admin:admin@mongodb-0.mongodb-service.default.svc.cluster.local:27017,mongodb-1.mongodb-service.default.svc.cluster.local:27017,mongodb-2.mongodb-service.default.svc.cluster.local:27017/?replicaSet=my_cluster"
  APP_PORT: "3001"
