apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - name: http-backend
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 31223

  type: NodePort
